CREATE TABLE debug_log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    module_name VARCHAR2(100),
    line_no NUMBER,
    log_level NUMBER(1),       -- Added to support INFO, WARN, ERROR
    log_message VARCHAR2(4000),
    session_id VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID')
);
